sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tS2HgVG9deQiHYAQ8Yc
    access-key-secret: K2w5lYeDfdgwjH6Ov0yH83jkVWMsi9
    bucket-name: szl-bucket-4test
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx0bf28af5c12020c5
    secret: 7588719f5a7031e8fef1ec357bf8623c
